
#Client-only settings
[client]
	#Show Entity Actives Potions on Overlay ?
	showEntityActivesPotions = false
	#Only use 'TOP_LEFT' or 'BOTTOM_LEFT' positions. ('TOP_RIGHT' and 'BOTTOM_RIGHT' W.I.P) 
	#Allowed Values: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
	overlayPosition = "TOP_LEFT"
	#Show Entity Name On Overlay ?
	showEntityNameInOverlay = false
	#Show InGame Damage Indicator Overlay ?
	showInGameOverlay = false
	#Show Entity Stats On Overlay ?
	showEntityStatsInOverlay = false
	#Display huge or little potion effect icons
	showPotionInfo = false

