
#World Generation Settings
[world_generation]
	#The probability of a dungeon getting generated on each fitting chunk.
	#Range: 1.0E-4 ~ 1.0
	dungeon_probability = 0.16

#Dungeon Settings
[dungeon]
	#If set to true, the dungeon generation will ignore the biome blacklist and generate dungeons in any overworld biome.
	ignore_overworld_blacklist = false
	#Defines if bridges should be used in dungeons. (Bridges are built if there is a certain amout of air under a corridor segment.
	build_bridges = true
	#The number of different entities per spawner. Increasing the number increases the diversity of the monster equipment.
	#Range: 1 ~ 128
	spawner_entities = 8
	#The minumum amount of rooms for each dungeon layer.
	#Range: 0 ~ 16
	layer_min_additions = 5
	#The amount of extra rooms per dungeon layer. A random number in the range [0 ~ layer_extra_additions-1] will be used.
	#Range: 1 ~ 16
	layer_extra_additions = 6

