
#Options that allow to disable/enable Univesal Clock and adjust it
["Universal Clock HUD"]
	#Position of Universal Clock on X axis of the screen.
	#Range: -32768 ~ 32768
	clockHudX = 30
	#Whether or not Universal Clock should have background.
	clockHudBackgroundEnabled = true
	#Whether or not Universal Clock should be displayed in the HUD.
	clockHudEnabled = false
	#Visible size of the Universal Clock.
	#Range: -32768.0 ~ 32768.0
	clockHudScale = 1.0
	#Whether or not Universal Clock should be hidden when chat screen is opened.
	clockHudHideInChat = true
	#Position of Universal Clock on Y axis of the screen.
	#Range: -32768 ~ 32768
	clockHudY = 20

