
["Spawn rates"]
	#
	#Crystals spawn rate (min=1 ; max=50 ; default=15)
	#Range: 1 ~ 50
	effectcrystals_spawnrate = 15
	#
	#Big speleothems spawn rate (min=1 ; max=50 ; default=16)
	#Range: 1 ~ 50
	big_speleothems_spawnrate = 16
	#
	#Mosses spawn rate (min=1 ; max=50 ; default=16)
	#Range: 1 ~ 50
	mosses_spawnrate = 16
	#
	#Pebbles spawn rate (min=1 ; max=50 ; default=18)
	#Range: 1 ~ 50
	pebbles_spawnrate = 18
	#
	#Pillars spawn rate (min=1 ; max=50 ; default=20)
	#Range: 1 ~ 50
	pillars_spawnrate = 20
	#
	#Cabins spawn rate (min=1 ; max=20 ; default=5)
	#Range: 1 ~ 20
	cabins_spawnrate = 5
	#
	#Rock piles spawn rate (min=1 ; max=50 ; default=14)
	#Range: 1 ~ 50
	rockpiles_spawnrate = 14
	#
	#Speleothems spawn rate (min=1 ; max=50 ; default=24)
	#Range: 1 ~ 50
	speleothems_spawnrate = 24
	#
	#Limestone patches spawn rate (min=1 ; max=50 ; default=6)
	#Range: 1 ~ 50
	limestone_spawnrate = 6
	#
	#Sanstone patches spawn rate (min=1 ; max=50 ; default=4)
	#Range: 1 ~ 50
	sandstone_spawnrate = 4
	#
	#Packed ice patches spawn rate (min=1 ; max=50 ; default=6)
	#Range: 1 ~ 50
	ice_spawnrate = 6
	#
	#Lavastone patches spawn rate (min=1 ; max=50 ; default=6)
	#Range: 1 ~ 50
	lavastone_spawnrate = 6
	#
	#Dungeons spawn rate (min=1 ; max=20 ; default=3)
	#Range: 1 ~ 20
	dungeons_spawnrate = 3
	#
	#Icy dungeons spawn rate (min=1 ; max=20 ; default=2)
	#Range: 1 ~ 20
	dungeons_ice_spawnrate = 2
	#
	#Sandstone dungeons spawn rate (min=1 ; max=20 ; default=2)
	#Range: 1 ~ 20
	dungeons_sandstone_spawnrate = 2

["Spawn conditions"]
	#
	#Generate stones noise
	gen_noise = false
	#
	#Generate tall decorations (double block)
	gen_decorations_tall = true
	#
	#Generate ice that can melt (can cause lag issues if true)
	gen_frosted_ice = false
	#
	#Generate sandstone in deserts
	gen_sandstone = true
	#
	#Generate mushrooms
	gen_mushrooms = true
	#
	#Generate pillars of stone
	gen_pillars = false
	#
	#Generate ice blocks in cold biomes
	gen_ice = true
	#
	#Generate cabins
	gen_cabins = true
	#
	#Generate alternate stones
	gen_stones = true
	#
	#Generate dungeons
	gen_dungeons = true
	#
	#Generate pebbles, rocks and speleothems
	gen_decorations = true

