
[foods]
	#Enable or disable the fish-based foods.
	fish_foods_enabled = true
	#Enable or disable the sweet-berry-based foods.
	berry_foods_enabled = true
	#Enable or disable the caramel-based foods.
	caramel_foods_enabled = true

[combat]
	#Disables friendly fire against pets.
	friendly_fire = true
	#Enable or disable the mod's bows.
	bows_enabled = true
	#Disables the new combat changes brought on by this mod.
	combat_tweaks = true

[misc]
	#Enable or disable the music discs (music still registers).
	music_discs_enabled = true

