
#Server and Client side changes.
[common]
	#Small Farlander house rarity (higher number = lower spawnrate)
	smallHouseSpawnRate = 2
	#Medium Farlander house rarity (higher number = lower spawnrate)
	mediumHouseSpawnRate = 3
	#Large Farlander house rarity (higher number = lower spawnrate)
	largeHouseSpawnRate = 4
	#Elder Farlander house rarity (higher number = lower spawnrate)
	elderHouseSpawnRate = 5
	#Farlander Loot Well rarity (higher number = lower spawnrate)
	farlanderLootWellSpawnRate = 10
	#Obsidian Spire rarity (higher number = lower spawnrate)
	obsidianSpireSpawnRate = 3

