
#Server and Client side changes.
[common]
	#Small Farlander house rarity (higher number = lower spawnrate)
	smallHouseSpawnRate = 5
	#Medium Farlander house rarity (higher number = lower spawnrate)
	mediumHouseSpawnRate = 6
	#Large Farlander house rarity (higher number = lower spawnrate)
	largeHouseSpawnRate = 7
	#Elder Farlander house rarity (higher number = lower spawnrate)
	elderHouseSpawnRate = 8
	#Farlander Loot Well rarity (higher number = lower spawnrate)
	farlanderLootWellSpawnRate = 12
	#Obsidian Spire rarity (higher number = lower spawnrate)
	obsidianSpireSpawnRate = 5

