#Generate Dust Wastelands in the world [true / false ]
dustWastelandGeneration = false
#Generate Mystical Forests in the world [true / false]
mysticalForestGeneration = true
#Generate Corrupted Forests in the world [true / false ]
corruptedForestGeneration = false
#Generate Terracotta Plains in the world [true / false ]
terracottaPlainsGeneration = true
#Generate Fields in the world [true / false]
fieldGeneration = true

