#Enable MoreProgression rock block variants in the game (Marble, Limestone, and Basalt) [true / false]
rockBlocksEnabled = true
#Enable the ender infuser block in the game [true / false]
enderInfuser = true
#Enable mystiwood wood type in the game [true / false]
mystiwoodWoodEnabled = true
#Enable the crusher block in the game [true / false]
crusherEnabled = true
#Enable the cherry wood type in the game [true / false]
cherryWoodEnabled = true
#Enable redwood wood type in the game [true / false]
redwoodWoodEnabled = true
#Enable silverwood wood type in the game [true / false]
silverwoodWoodEnabled = true

