#Generate Ianite Ore in the world [true / false ]
ianiteOreGeneration = true
#Generate Basalt in the world [true / false ]
basaltGeneration = false
#Generate Marble in the world [true / false ]
marbleGeneration = false
#Generate Fossils in the world [true / false ]
fossilGeneration = true
#Generate Tritanium Ore in the world [true / false ]
tritaniumOreGeneration = true
#Generate Silverwood Trees in the world [true / false ]
silverwoodTreeGeneration = true
#Generate Ender Ore in the world [true / false ]
enderOreGeneration = true
#Generate Limestone in the world [true / false ]
limestoneGeneration = true
#Generate Blueberry Bushes in the world [true / false ]
blueberryBushGeneration = true
#Generate Glorium Ore in the world [true / false ]
gloriumOreGeneration = true

