
#Ore Generation
[oregen]

	#Copper ore generation.
	[oregen.Copper_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		minY = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		maxY = 0
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 1

	#Silver ore generation.
	[oregen.Silver_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		minY = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		maxY = 0
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 1

	#Lead ore generation.
	[oregen.Lead_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		minY = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		maxY = 0
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 1

	#Quicksilver ore generation.
	[oregen.Quicksilver_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 3
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		minY = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		maxY = 16
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 1

	#Amethyst ore generation.
	[oregen.Amethyst_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		minY = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		maxY = 0
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 1

	#Tin ore generation.
	[oregen.Tin_oregen]
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		oreChances = 0
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 0
		minY = 24
		#Number of veins per chunk (set to 0 to disable).
		#Range: 0 ~ 256
		maxY = 0
		#Max size of the vein.
		#Range: 1 ~ 256
		veinSize = 8

#Mob Spawn Configuration
[mob_spawns]

	#Frog spawn config.
	[mob_spawns.Frog_spawn]
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 2
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 4
		#List of biome types to spawn.
		biomes = "SWAMP,JUNGLE,BEACH,RIVER,"
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 6

	#Beetle spawn config.
	[mob_spawns.Beetle_spawn]
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 2
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 4
		#List of biome types to spawn.
		biomes = "SWAMP,JUNGLE,FOREST,PLAINS,"
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 5

	#Sprout spawn config.
	[mob_spawns.Sprout_spawn]
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 2
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 4
		#List of biome types to spawn.
		biomes = "JUNGLE,LUSH,MAGICAL,RIVER,FOREST,BEACH,"
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 2

	#Silver Fox spawn config.
	[mob_spawns."Silver Fox_spawn"]
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 1
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 3
		#List of biome types to spawn.
		biomes = "FOREST,COLD,CONIFEROUS,"
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 4

	#Deer spawn config.
	[mob_spawns.Deer_spawn]
		#Min to spawn in a group.
		#Range: 0 ~ 256
		min = 2
		#Max to spawn in a group.
		#Range: 0 ~ 256
		max = 4
		#List of biome types to spawn.
		biomes = "FOREST,COLD,CONIFEROUS,PLAINS,"
		#Chance to spawn (set to 0 to disable).
		#Range: 0 ~ 256
		spawnChance = 6

