
[capsule]
	# This number decides that how many effect names are render behind the capsule name
	#Range: 0 ~ 5
	effectRenderCount = 3
	# Set this to true will give filled capsule the enchanted glowing render effect
	glowWithEffect = false

[pendant]
	# Set this to true will mute the game status which pops up while capsule being used from pendant
	muteCapsuleUsage = false

[misc]
	# Set this to true will render the icon in the ingame HUD. This is false by default
	renderNVNFHUD = false

