
[capsule]
	# This number represents the stack limit of capsule inside the pendant
	#Range: 1 ~ 4096
	stackSize = 128
	# This number decides how long is the effect in a Capsule and the amount extracts from the potion while crafting
	#Range: 40 ~ 400
	capacity = 100

[recipe]
	# Set this to true will enable the crafting recipe of Nether Wart Dust
	enableWartDust = false
	# This defines the maximum amount of Instant Catalyst the player is allowed to placed in the crafting grid to dup output. Set to 0 to disable this feature
	#Range: 0 ~ 63
	instantCatalystAllowed = 7
	# Set this to true will remove a certain effect from a potion item if its duration is less than required in recipe
	removeExcessDuration = false
	# Set this to true will allow Potion Capsules to be combined in crafting grids
	allowCombine = true

[misc]
	# Set this to true will automatically replace any NightVision with NightVisionNoFlicker, a wrapper effect just to solve the vanilla flickering NightVision
	replaceNvWithNvnf = true

