#Whether the search bar will be focused by default when opening containers
autoFocus = false
#Minimum size a container must be for a search bar to be added
#Range: > 0
minimumContainerSize = 27

