
#General Configuration
[general]
	#Format to display time in. See http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns
	timeformat = "h:mm a"
	#The title of the Minecraft window. Leave blank to keep the default window title for your version of Minecraft.
	#Some special values that will be inserted at runtime:
	#%mcver% -> The current Minecraft version
	#%modcount% -> Number of loaded mods
	#%time% -> Current system time
	#
	windowtitle = "TNP Limitless"

