
#Client only settings
[client]
	#This causes the deletion slot to delete items instantly, similar to Creative Mode.
	instantDeletion = false

	[client.gui]

		[client.gui."net/minecraft/client/gui/screen/inventory/InventoryScreen"]
			#True if this screen should have a trash slot.
			slotX = 60
			#The x coordinate of the slot relative to the anchor.
			slotY = 83
			#The y coordinate of the slot relative to the anchor.
			anchorX = 0.5
			#The x coordinate of the anchor point for the slot position.
			anchorY = 0.5
			#The y coordinate of the anchor point for the slot position.
			enabled = true

